#set page(margin:20pt)

#grid(
  columns: (auto, auto, 1fr),
  rows: (auto, 10pt),
  align: (left, center, left),
  gutter: 3pt,
  [_Declaration_], [$#sym.arrow.double.l$], [_Statement_ _Parameters_ $<-$ _Declaration_],
  [], [], [$#sym.bar$ _Statement_],
  [], [], [],
  [_Parameters_], [$#sym.arrow.double.l$], [_ID_ _Parameters_],
  [], [], [$#sym.bar$ $epsilon$],
  [], [], [],
  [_Statement_], [$#sym.arrow.double.l$], [_Statement_ $?$ _Statement_ $:$ _Statement_],
  [], [], [$#sym.bar$ $\$$ _Expression_],
  [], [], [$#sym.bar$ _Statement_ $*$$*$ _Expression_],
  [], [], [$#sym.bar$ _Expression_],
  [], [], [],
  [_Expression_], [$#sym.arrow.double.l$], [_ID_ $!$$<$ int],
  [], [], [$#sym.bar$ _LogicOr_],
  [], [], [],
  [_LogicOR_], [$#sym.arrow.double.l$], [_LogicAnd_ $|$$|$ _LogicOR_],
  [], [], [$#sym.bar$ _LogicAnd_],
  [], [], [],
  [_LogicAnd_], [$#sym.arrow.double.l$], [_Equality_ $\&$$\&$ _LogicAnd_],
  [], [], [$#sym.bar$ _Equality_],
  [], [], [],
  [_Equality_], [$#sym.arrow.double.l$], [_Comparison_ $(= | ! =)$ _Equality_],
  [], [], [$#sym.bar$ _Comparison_],
  [], [], [],
  [_Comparison_], [$#sym.arrow.double.l$], [_Term_ $( < | <= | > | >=)$ _Comparison_],
  [], [], [$#sym.bar$ _Term_],
  [], [], [],
  [_Term_], [$#sym.arrow.double.l$], [_Factor_ $( + | - )$ _Term_],
  [], [], [$#sym.bar$ _Term_],
  [], [], [],
  [_Factor_], [$#sym.arrow.double.l$], [_Unary_ $( * | \/ )$ _Factor_],
  [], [], [$#sym.bar$ _Unary_],
  [], [], [],
  [_Unary_], [$#sym.arrow.double.l$], [( ! | - ) _Unary_],
  [], [], [$#sym.bar$ _Call_],
  [], [], [],
  [_Call_], [$#sym.arrow.double.l$], [_Primary_ $>>$ _Arguments_],
  [], [], [$#sym.bar$ _Primary_],
  [], [], [],
  [_Arguments_], [$#sym.arrow.double.l$], [_Primary_ _Arguments_],
  [], [], [$#sym.bar$ $epsilon$],
  [], [], [],
  [_Primary_], [$#sym.arrow.double.l$], [_NUMBER_ $#sym.bar$ _STRING_ $#sym.bar$ _PATH_ $#sym.bar$ _ID_ $#sym.bar$ _PARENTH_EXPR_ $#sym.bar$ _BLOCK_ $#sym.bar$ _ARRAY_ ],
  [], [], [],
  [_NUMBER_], [$#sym.arrow.double.l$], [$"int"^* #sym.bar "int"^*."int"^+$],
  [], [], [],
  [_STRING_], [$#sym.arrow.double.l$], ["$"char"^*$"],
  [], [], [],
  [_PATH_], [$#sym.arrow.double.l$], ['$"char"^*$'],
  [], [], [],
  [_ID_], [$#sym.arrow.double.l$], [$"char"^*$],
  [], [], [],
  [_PARENTH_EXPR_], [$#sym.arrow.double.l$], [( _Expression_ )],
  [], [], [],
  [_BLOCK_], [$#sym.arrow.double.l$], [{ _Declaration_$attach(,tr:*)$ }],
)
