type lexeme = LEFT_ARROW | PLUS_INF | MINUS_INF | SUP_SUP | DOLL | QUEST_MARK | COLON | LEFT_PAREN
  | RIGHT_PAREN | TIME_TIME | CARET | PLUS | MINUS | TIME | INF | INF_EQUAL | SUP | SUP_EQUAL | EQUAL
  | NUMBER | STRING | ID | LEFT_BRACE | RIGHT_BRACE | LEFT_SQ_BRACK | RIGHT_SQ_BRACK | BANG | BANG_INF
  | UNDERSCORE | AMPERSAND | VERT_BAR | SLASH | BACKSLASH | AMPERSAND_AMPERSAND | VERT_BAR_VERT_BAR
  | DOT | COMMA | LINE_BREAK

type value = STRING of string | FLOAT of float

type token = { lexeme : lexeme; value : value; line : int }
